project:
  type: website
  render:
    - "*.{qmd}"
  preview:
    port: 4200
    browser: true

website:
  title: max ostapenko
  description: Max Ostapenko's personal website
  site-url: https://maxostapenko.com/
  image: static/images/profile.jpg
  favicon: static/images/logo.png
  twitter-card:
    creator: "@themax_o"
  open-graph: true
  back-to-top-navigation: true
  google-analytics:
    tracking-id: G-9B07JCCPN7
    storage: none
  repo-url: https://github.com/max-ostapenko/website-source
  repo-actions: []

  navbar:
    logo: static/images/logo.png
    left:
      - text: home
        href: index.qmd
      - sidebar:learning
      - text: blog
        href: blog.qmd
      - sidebar:projects
      - text: about
        href: about.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/max-ostapenko/
      - icon: github
        href: https://github.com/max-ostapenko
      - icon: twitter
        href: https://twitter.com/themax_o/

  sidebar:
    - id: learning
      contents:
        - auto: learning/*.qmd

    - id: projects
      contents:
        - auto: projects/**
        - text: ---
        - section: external
          contents:
            - text: Web Almanac - Privacy
              href: https://almanac.httparchive.org/en/2022/privacy
              target: _blank

  page-footer:
    left: |
      Built with [Quarto](https://quarto.org).
    center: "© 2024 Max Ostapenko"
    right:
      - icon: rss
        href: blog.xml

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: static/styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
    fig-cap-location: margin
    code-fold: true
    code-line-numbers: true

execute:
  freeze: true
