---
title: Selected knowledge sources
---

## read

- [Marty Cagan (SVPG)](https://www.svpg.com/articles/) - Practical advice on building successful tech products and teams.
- [Benedict Evans](https://www.ben-evans.com/benedictevans/) - Trends and insights on tech, media, and mobile industries.
- [Martin Fowler](https://martinfowler.com/) - Deep dives into software architecture and agile practices.
- [Paul Graham](http://www.paulgraham.com/articles.html) - Essays on startups, technology, and entrepreneurship.
- [John Cutler](https://cutlefish.substack.com/) - Product management insights focused on systems thinking and collaboration.
- [Elena Verna](https://elenaverna.substack.com/) - Growth strategy and product-led growth for tech companies.
- [Teresa Torres](https://www.producttalk.org/blog/) - Continuous discovery habits and product decision-making best practices.

and [follow me on goodreads.com](https://www.goodreads.com/friend/add_as_friend/70245794?return_url=%2Fmax_ostapenko)

## listen

- [Matt Abrahams (Think Fast, Talk Smart)](https://www.gsb.stanford.edu/business-podcasts/think-fast-talk-smart-podcast) - Insights on effective communication strategies from experts.
- [Lex Fridman](https://lexfridman.com/podcast/) - Deep conversations with scientists, thinkers, and creators.
- [Eric Seufert (MobileDevMemo)](https://mobiledevmemo.com/) - In-depth analysis of mobile app growth and monetization.
- [Marketecture](https://www.marketecture.tv/pages/podcasts) - Expert interviews on adtech, martech, and digital strategy.
- [Lenny Rachitsky](https://www.lennyspodcast.com/) - Tips on scaling products and building teams from top operators.
- [Talks at Google](https://www.youtube.com/TalksAtGoogle) - Thought-provoking talks from innovators and leaders across industries.
- [Melissa Perri (Product Thinking)](https://produxlabs.com/product-thinking) - A dive into product management, strategy, and leadership.

## visit

| Date | Event | Location | Recordings |
|---------|--------------------------------------------|------------------|
| Oct 11, 2024 | [just product](https://www.product-masterclass.com/en/just-product-2023) | Munich, DE |
| Jan 27, 2025 | [Superweek](https://superweek.hu/) | Hungary |

```{=html}
<button class="btn btn-link" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">Past events</button>
<div class="collapse" id="collapseExample">
 <div class="card card-body">
```
| Date | Event | Location | Recordings |
|---------|--------------------------------------------|------------------|
| Sep 21, 2024 | [Measurecamp Berln](https://berlin.measurecamp.org/) | Berln, DE |
| Sep 13, 2024 | [Product at Heart](https://productatheart.com/conference) | Hamburg, DE |
| Aug 30, 2024 | [ProductCamp Berlin](https://www.productcampberlin.org/) | Berlin, DE |
| Jun 19, 2024 | [growth marketing SUMMIT](https://www.growthmarketingsummit.com) | Frankfurt, DE |
| Jun 17, 2024 | [Industry EUROPE](https://www.industryconference.com/europe) | Dublin, IR |
| Jun 13, 2024 | [ACE!](https://aceconf.com/) | Krakow, PL |
| Jun 4, 2024 | [SaaStr Europa](https://www.saastreuropa2024.com/) | London, UK |
| May 29, 2024 | [Dublin Tech Summit](https://dublintechsummit.tech/) | Dublin, IR |
| May 15, 2024 | [La Product Conf](https://www.laproductconf.com/) | Paris, FR + Madrid, ES |
| May 10, 2024 | [Product Led Summit](https://world.productledalliance.com/location/amsterdam/speakers) | Amsterdam, NL |
| Apr 15, 2024 | [Web Summit](https://rio.websummit.com/) | Rio de Janeiro, BR |
| Mar 20, 2024 | [UX Copenhagen](https://uxcopenhagen.com/) | Copenhagen, DK |
| Feb 20, 2024 | [ProductCon](https://productschool.com/productcon/london-2024) | London, UK + online |
