title: Max Ostapenko
author: Max Ostapenko
linkedin: https://www.linkedin.com/in/max-ostapenko/
github: https://github.com/max-ostapenko
twitter: https://twitter.com/themax_o
calendar: https://cal.com/max-ostapenko/30min
