project:
  type: website
  render:
    - "*.{qmd}"
  output-dir: ../_site
  resources:
    - static/**
  preview:
    port: 4200

website:
  title: max ostapenko
  description: Data Product Management | Max Ostapenko
  site-url: https://maxostapenko.com/
  image: static/images/profile.jpg
  favicon: static/images/logo.svg
  twitter-card:
    creator: "@themax_o"
    card-style: summary
  open-graph: true
  back-to-top-navigation: true
  page-navigation: true

  navbar:
    logo: static/images/logo.svg
    left:
      - text: home
        href: /
      - sidebar:learning
      - text: blog
        href: posts/
      - sidebar:projects
      - text: about
        href: about/
    tools:
      - text: LinkedIn profile
        icon: linkedin
        href: https://www.linkedin.com/in/max-ostapenko/
        target: _blank
      - text: GitHub account
        icon: github
        href: https://github.com/max-ostapenko
        target: _blank
      - text: Twitter account
        icon: twitter
        target: _blank
        href: https://twitter.com/themax_o/
      - text: Appointments calendar
        icon: calendar-week
        href: appointments/

  sidebar:
    - id: learning
      contents:
        - auto: learning/**

    - id: projects
      contents:
        - auto: projects/**
        - text: ---
        - section: HTTP Archive
          contents:
            - text: Web Almanac - Privacy
              href: https://almanac.httparchive.org/en/2022/privacy
              target: _blank

  page-footer:
    left: |
      Built with [Quarto](https://quarto.org).
    center: "© 2024 Max Ostapenko"
    right:
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      light: flatly
    toc: true
    toc-location: right
    link-external-icon: false
    link-external-newwindow: true
    fig-cap-location: margin
    code-tools:
      source: false
      toggle: true
    code-line-numbers: false
    code-link: true
    highlight-style: github
    code-overflow: wrap
    page-layout: full
    lightbox: true
    smooth-scroll: true
    notebook-links: false
    code-fold: true
    code-summary: "Show code"
    fig-align: center
    mermaid:
          theme: neutral
    include-in-header: static/html/gtm_code_head.html
    include-before-body: static/html/gtm_code_body.html
