project:
  type: website
  render:
    - "*.{qmd}"
  output-dir: ../_site
  resources:
    - static/**
  preview:
    port: 4200
  post-render:
    - python3 ../scripts/clean_sitemap.py

website:
  title: max ostapenko
  description: Data Product Management | Max Ostapenko
  site-url: https://maxostapenko.com/
  image: https://maxostapenko.com/static/images/profile.jpg
  favicon: static/images/logo.svg
  twitter-card:
    creator: "@themax_o"
    card-style: summary
  open-graph: true
  back-to-top-navigation: true
  bread-crumbs: false

  navbar:
    logo: static/images/logo.svg
    logo-alt: Logo
    background: "#174EA6"
    left:
      - sidebar:learning
      - text: blog
        href: posts/
      - sidebar:projects
      - text: about
        href: about/

    tools:
      - text: LinkedIn profile
        icon: linkedin
        href: https://www.linkedin.com/in/max-ostapenko/
        target: _blank
      - text: GitHub account
        icon: github
        href: https://github.com/max-ostapenko
        target: _blank
      - text: Twitter account
        icon: twitter
        target: _blank
        href: https://x.com/themax_o/
      - text: Appointments calendar
        icon: calendar-week
        href: appointments/

  sidebar:
    - id: learning
      contents:
        - auto: learning/**

    - id: projects
      contents:
        - auto: projects/**
        - text: ---
        - section: HTTP Archive
          contents:
            - text: Web Almanac - Privacy
              href: https://almanac.httparchive.org/en/2022/privacy
              target: _blank

  page-footer:
    left: |
      Built with [Quarto](https://quarto.org)
    right:
      - icon: rss
        href: posts.xml

  draft-mode: gone

format:
  html:
    page-layout: full
    toc: true
    canonical-url: true
    toc-location: right
    link-external-icon: false
    link-external-newwindow: true

    fig-align: center
    fig-cap-location: margin

    code-fold: true
    code-summary: "Show code"
    code-tools:
      source: false
      toggle: true
    code-line-numbers: false
    code-overflow: wrap
    highlight-style: github
    mermaid:
      theme: neutral
    notebook-links: false

    lightbox: true
    image-lazy-loading: true

    include-in-header: static/html/gtm_code_head.html
    include-before-body: static/html/gtm_code_body.html
