project:
  type: website
  render:
    - "*.{qmd}"
  output-dir: ../_site
  resources:
    - static/**
  preview:
    port: 4200

website:
  title: max ostapenko
  description: Data Product Management | Max Ostapenko
  site-url: https://maxostapenko.com/
  image: static/images/profile.jpg
  favicon: static/images/logo.svg
  twitter-card:
    creator: "@themax_o"
  open-graph: true
  back-to-top-navigation: true
  page-navigation: true
  google-analytics:
    tracking-id: G-9B07JCCPN7
    storage: none
  repo-url: https://github.com/max-ostapenko/website-source
  repo-actions: []
  repo-subdir: src/

  navbar:
    logo: static/images/logo.svg
    left:
      - text: home
        href: index.qmd
      - sidebar:learning
      - text: blog
        href: posts/index.qmd
      - sidebar:projects
      - text: about
        href: about/index.qmd
    tools:
      - icon: linkedin
        text: LinkedIn profile
        href: https://www.linkedin.com/in/max-ostapenko/
      - icon: github
        text: GitHub account
        href: https://github.com/max-ostapenko
      - icon: twitter
        text: Twitter account
        href: https://twitter.com/themax_o/

  sidebar:
    - id: learning
      contents:
        - auto: learning/**

    - id: projects
      contents:
        - auto: projects/**
        - text: ---
        - section: External
          contents:
            - text: Web Almanac - Privacy
              href: https://almanac.httparchive.org/en/2022/privacy
              target: _blank

  page-footer:
    left: |
      Built with [Quarto](https://quarto.org).
    center: "© 2024 Max Ostapenko"
    right:
      - icon: rss
        href: blog.xml

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-location: right
    link-external-icon: false
    link-external-newwindow: true
    fig-cap-location: margin
    code-tools:
      source: false
      toggle: true
    code-line-numbers: false
    code-link: true
    highlight-style: github
    code-overflow: wrap
    page-layout: full
    lightbox: true
    smooth-scroll: true
    notebook-links: false
    code-fold: true
    code-summary: "Show code"
