name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: make env

      - id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: 'projects/390347019852/locations/global/workloadIdentityPools/test/providers/github-runner'
          service_account: 'github-action-website-source@max-ostapenko.iam.gserviceaccount.com'
          create_credentials_file: true

      - name: Deploy to Firebase Preview
        if: github.event_name == 'pull_request'
        run: npm run deploy-preview -- pr-${{ github.event.pull_request.number }}

      - name: Deploy to Firebase Live
        if: github.event_name == 'push'
        run: npm run deploy
