name: Deploy to Firebase Hosting on PR
on:
  pull_request

jobs:
  build_and_preview:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: make env

      - id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: https://iam.googleapis.com/projects/390347019852/locations/global/workloadIdentityPools/test/providers/github-runner
          service_account: github-action-website-source@max-ostapenko.iam.gserviceaccount.com
          create_credentials_file: true

      - name: Export Firebase credentials
        run: echo "FIREBASE_SERVICE_ACCOUNT=$(cat "${{ steps.auth.outputs.credentials_file_path }}" | tr -d '\n')" >> $GITHUB_ENV

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ env.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: max-ostapenko
          expires: 7d
