name: Render and Deploy
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

# you need these permissions to publish to GitHub pages
# permissions:
#     contents: write
#     pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # From https://github.com/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v3

      # See more at https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md

      # To publish to Netlify or GitHub Pages, uncomment
      # the appropriate block below

      - name: Publish to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAX_OSTAPENKO }}'
          channelId: staging
          projectId: max-ostapenko

      - name: Publish to Netlify
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see top of this yaml)
      # - name: Publish to GitHub Pages (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: gh-pages
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
